Don't crash when server is down
Response is undefined when the connection cannot be established, which
caused res.statusCode to blow up with:
```
/usr/src/app/node_modules/share2nightscout-bridge/index.js:238
        console.log("Error refreshing token", err, res.statusCode, body);
                                                      ^

TypeError: Cannot read property 'statusCode' of undefined
```